name: Build + SBOM + Semgrep

on:
  push:
    branches: ['master']   # gerekirse 'main' de ekle
  pull_request:
  workflow_dispatch:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # gitleaks/geçmiş istersek lazım olur

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # lock yoksa cache uyarısı vermesin istiyorsan bu satırı kaldır:
          cache: 'npm'

      # ---- DEPENDENCY INSTALL (ci varsa ci, yoksa install) ----
      - name: Install deps (prefer npm ci)
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found -> npm ci"
            npm ci
          else
            echo "No lock file -> npm install"
            npm install
          fi

      - name: Build
        run: |
          if jq -r '.scripts.build // empty' package.json >/dev/null 2>&1; then
            npm run build
          else
            echo "No build script found, skipping"; exit 0
          fi

      # --- Syft SBOM ---
      - name: Install Syft
        run: |
          SYFT_VERSION="v1.20.0"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin "$SYFT_VERSION"
          syft version

      - name: Generate SBOM
        run: |
          mkdir -p sbom
          syft dir:. -o spdx-json=sbom/sbom.spdx.json
          syft dir:. -o cyclonedx-json=sbom/sbom.cdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-node
          path: sbom/*.json
          retention-days: 30

      # --- Semgrep SAST ---
      - name: Run Semgrep (autoconfig)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
          sarifFile: semgrep.sarif

      - name: Upload Semgrep SARIF
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      # --- Gitleaks ---
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true

      - name: Upload Gitleaks SARIF
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
