# .github/workflows/security.yml
name: Security & SBOM

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"   # her pazartesi 06:00 (Europe/Istanbul +03:00)

permissions:
  contents: read
  actions: read
  security-events: write   # (ileride Code Scanning/Grype eklersek lazım)
  id-token: none

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest
    env:
      BUILD_CMD: "echo 'no-op build'"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          set -euo pipefail
          echo "Running build: $BUILD_CMD"
          bash -lc "$BUILD_CMD"

      - name: Install Syft (pinned)
        run: |
          set -euo pipefail
          SYFT_VERSION="v1.20.0"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin "$SYFT_VERSION"
          syft version

      - name: Generate SBOM (SPDX & CycloneDX)
        run: |
          set -euo pipefail
          mkdir -p sbom
          # Kaynak koddan bağımlılık çıkarımı:
          syft dir:. -o spdx-json=sbom/sbom.spdx.json
          syft dir:. -o cyclonedx-json=sbom/sbom.cdx.json
          # (Opsiyonel) Build çıktısını da tara: ./build, ./dist, ./target vs.
          if [ -d build ]; then syft dir:build -o cyclonedx-json=sbom/binary.cdx.json; fi

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom/*.json
          retention-days: 30
