name: Build + SBOM + Semgrep

on:
  push:
    branches: ['master']
  pull_request:
  workflow_dispatch:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write   # SARIF için şart

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # --- Syft SBOM ---
      - name: Install Syft
        run: |
          SYFT_VERSION="v1.20.0"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin "$SYFT_VERSION"
          syft version

      - name: Generate SBOM
        run: |
          mkdir -p sbom
          syft dir:. -o spdx-json=sbom/sbom.spdx.json
          syft dir:. -o cyclonedx-json=sbom/sbom.cdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-node
          path: sbom/*.json
          retention-days: 30

      # --- Semgrep SAST ---
      - name: Run Semgrep (autoconfig)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
          sarifFile: semgrep.sarif

      - name: Upload Semgrep results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      #--- gitleaks---

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true   # bulgu olursa pipeline fail etmesin

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
      
